server:
  port: 84
spring:
  application:
    name: nacos-order-consumer
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.124.128:8848
    sentinel:
      transport:
        dashboard: 192.168.124.128:8080
        port: 8719
      datasource:
        ds1:
          nacos:
           server-addr: 192.168.124.128:8848
           data-id: ${spring.application.name}
           group-id: DEFAULT_GROUP
           data-type: json
           rule-type: flow

service-url:
  nacos-user-service: http://naocs-payment-provider

#激活sentinel对feign的支持
feign:
  sentinel:
    enabled: true